### ISSUE TITLE
Pipenv manager seems to require .python-version file

### ISSUE THREAD

**Issue by joeka** [renovatebot/detect-tools#36]
[Since renovate uses detect-tools](https://github.com/renovatebot/renovate/commit/c3cf91b8b91475bc87dc390eb07753d866e9f76b) in the Pipenv manager, our pipeline fails because it can't find the .python-version file.

I don't have time to analyze it myself right now, but is it possible that [this](https://github.com/renovatebot/detect-tools/blob/8ca15d3ff987aee7509fb5a33e9b6fb80b508cec/src/manager/pipenv.ts#L174) fails if there is no .python-version file?
https://github.com/renovatebot/detect-tools/blob/8ca15d3ff987aee7509fb5a33e9b6fb80b508cec/src/manager/pipenv.ts#L174

The errors we get look like this:
``` json
{
  "name": "renovate",
  "level": 50,
  "logContext": "LCC-PiobRTXiuuKC5tW_q",
  "repository": "project/repo",
  "err": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/tmp/renovate/repos/azure/project/repo/.python-version",
    "message": "ENOENT: no such file or directory, open '/tmp/renovate/repos/azure/project/repo/.python-version'",
    "stack": "Error: ENOENT: no such file or directory, open '/tmp/renovate/repos/azure/project/repo/.python-version'"
  },
  "msg": "Repository has unknown error"
}
```

**Comment by joeka** [comment]
looks like it, but if I return null instead of calling fsReadFile [here](https://github.com/renovatebot/detect-tools/blob/8ca15d3ff987aee7509fb5a33e9b6fb80b508cec/src/fs.ts#L10C12-L10C22) the error above is not thrown and renovate exits with exit code 0 instead of 1.

**Comment by zharinov** [comment]
Ohh, I think I get it

**Comment by joeka** [comment]
The function is async?

**Comment by joeka** [comment]
yes! Thank you :)

**Comment by zharinov** [comment]
@viceice Could you please force this detect-tools update in Renovate repo?

**Comment by viceice** [comment]
- https://github.com/renovatebot/renovate/pull/31028
